use std::path::PathBuf;

#[derive(clap::Parser)]
#[clap(name = "Wail")]
pub struct Wail {
    /// WADM manifest file (optional)
    #[clap(long = "wadm")]
    pub wadm: Option<PathBuf>,

    /// Components configuration file (optional)
    #[clap(long = "components")]
    pub components: Option<PathBuf>,

    /// Manifest name
    #[clap(long = "name", default_value = "generated-manifest")]
    pub name: String,

    /// Manifest version
    #[clap(long = "version", default_value = "0.1.0")]
    pub version: String,

    /// Manifest description
    #[clap(long = "description", default_value = "Generated by WADM Constructor")]
    pub description: String,
}
